// This file is auto-generated by the seed agent — do not edit manually.
// Run POST /api/admin/seed-lessons to seed these lessons into Supabase.

export interface LessonSeedDefinition {
  subjectSlug: string;
  topic: {
    title: string;
    slug: string;
    description: string;
    order_index: number;
    key_stage: string;
    estimated_minutes: number;
  };
  structure: {
    spark_json: {
      hook_type: string;
      hook_content: string;
      opening_question: string;
      expected_responses: string[];
      prior_knowledge_integration: string;
    };
    explore_json: {
      concepts: Array<{
        id: string;
        title: string;
        explanation: string;
        analogy: string;
        real_example: string;
        check_question: string;
        common_mistake: string;
      }>;
      sequence_notes: string;
    };
    anchor_json: {
      method: string;
      prompt: string;
      mastery_indicators: string[];
      fallback_approach: string;
    };
    practise_json: {
      questions: Array<{
        id: string;
        question: string;
        difficulty: number;
        correct_answer: string;
        explanation: string;
        hint: string;
      }>;
    };
    create_json: {
      task_type: string;
      brief: string;
      scaffolding: string;
      real_world_connection: string;
      interest_placeholder: string;
    };
    check_json: {
      questions: Array<{
        type: string;
        question: string;
        what_correct_looks_like: string;
      }>;
    };
    celebrate_json: {
      fun_fact: string;
      next_topic_teaser: string;
      praise_templates: string[];
    };
  };
}

// ── Placeholder: will be replaced by lesson seed agent with 45 complete lessons ──
export const SEED_LESSONS: LessonSeedDefinition[] = [];
